#!/usr/bin/env python3

"""
Calibration-resolution sensitivity experiment.

This script evaluates how sensitive the final supervision scores are to the
resolution k of the synthetic ordinal calibration grid.

It requires a completed k=15 master calibration grid generated by:

    generate_calibration_grid.py

Expected default layout, relative to this script:

    generate_calibration_grid.py
    test_k_sensitivity.py

    calibration_grid/
    └── data/
        ├── calibration_meta.json
        ├── calibration_levels.json
        ├── summary_stats.json
        └── calibration_runtime.json

    dataset/
        └── ...

    k_sensitivity_results/
        └── ...

The calibration grid itself is generated only once at k=15. For each tested
resolution k in:

    {2, 3, 5, 7, 9, 11, 13, 15}

this script selects the corresponding approximately evenly spaced subset of
the k=15 master grid, recomputes the calibration statistics, and relabels the
same target examples.

The k=15 result is used as the high-resolution reference.

The script does not modify the source dataset or calibration data.

If no usable target examples can be loaded from dataset/, the script falls
back to using the k=15 calibration grid itself as the common target set.

Calibration metadata, EnergyPlus summaries, and runtime metadata are each
parsed only once. The analysis reports stage-level wall-clock timings rather
than using a persistent progress bar because no EnergyPlus simulations are run
during this experiment.

Default usage:

    python3 test_k_sensitivity.py

Optional explicit paths:

    python3 test_k_sensitivity.py \
        --calibration-dir ./calibration_grid \
        --dataset-dir ./dataset \
        --output-dir ./k_sensitivity_results
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
import time
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Sequence


# ---------------------------------------------------------------------------
# Experiment configuration
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent

DEFAULT_CALIBRATION_DIR = (
    SCRIPT_DIR
    / "calibration_grid"
)

DEFAULT_DATASET_DIR = (
    SCRIPT_DIR
    / "dataset"
)

DEFAULT_OUTPUT_DIR = (
    SCRIPT_DIR
    / "k_sensitivity_results"
)

EXPECTED_MAX_K = 15

K_VALUES = (
    2,
    3,
    5,
    7,
    9,
    11,
    13,
    15,
)

REQUIRED_PARAMETERS = (
    "wall_r_value",
    "roof_r_value",
    "hvac_heating_cop",
    "hvac_cooling_cop",
)

HVAC_SIM_FEATURE_CANDIDATES = (
    "Electricity:HVAC [J](Hourly)",
    "hvac_electricity",
    "hvac",
    "hvac_energy",
)

INSULATION_SIM_FEATURE_CANDIDATES = (
    "Heating Coil Heating Energy [J](Hourly)",
    "heating_coil",
    "heating_coil_energy",
    "insulation",
)


# ---------------------------------------------------------------------------
# Data containers
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExperimentPaths:
    """Resolved experiment paths."""

    calibration_dir: Path
    calibration_data_dir: Path
    dataset_dir: Path
    output_dir: Path


@dataclass(frozen=True)
class CalibrationConfig:
    """Configuration reconstructed from calibration_levels.json."""

    max_k: int
    k_values: tuple[int, ...]
    level_sets: Dict[
        str,
        tuple[int, ...],
    ]
    parameter_levels: Dict[
        str,
        tuple[float, ...],
    ]
    reference_k: str


@dataclass(frozen=True)
class CalibrationData:
    """
    Calibration artifacts loaded once for the complete experiment.

    Keeping these parsed objects in memory avoids repeatedly reparsing the
    potentially large calibration JSON files.
    """

    meta_records: List[
        Dict[str, Any]
    ]

    stat_records: List[
        Dict[str, Any]
    ]

    runtime_jobs: Dict[
        str,
        Dict[str, Any],
    ]


@dataclass(frozen=True)
class RawExample:
    """Raw target example before calibration."""

    example_id: str
    text_hvac: float
    text_insulation: float
    sim_hvac: float
    sim_insulation: float


@dataclass(frozen=True)
class Scaler:
    """Calibration statistics for one concept."""

    text_mean: float
    text_std: float
    sim_mean: float
    sim_std: float


@dataclass(frozen=True)
class LabeledExample:
    """Example after calibration and fusion."""

    example_id: str
    k_name: str
    hvac_label: float
    insulation_label: float
    overall_label: float


# ---------------------------------------------------------------------------
# Console timing
# ---------------------------------------------------------------------------

@contextmanager
def stage(
    number: int,
    total: int,
    description: str,
) -> Iterator[None]:
    """Print and time one major analysis stage."""
    print(
        f"[{number}/{total}] "
        f"{description}...",
        flush=True,
    )

    started = (
        time.perf_counter()
    )

    try:
        yield

    finally:
        elapsed = (
            time.perf_counter()
            - started
        )

        print(
            f"      done in "
            f"{elapsed:.2f} s"
        )
        print()


# ---------------------------------------------------------------------------
# Paths and JSON
# ---------------------------------------------------------------------------

def resolve_path(
    supplied: str | Path | None,
    default: Path,
) -> Path:
    """
    Resolve a command-line path.

    Explicit relative paths are interpreted relative to the shell's current
    working directory. Defaults are anchored to this script.
    """
    if supplied is None:
        return default.resolve()

    path = Path(
        supplied
    ).expanduser()

    if not path.is_absolute():
        path = (
            Path.cwd()
            / path
        )

    return path.resolve()


def build_paths(
    calibration_dir: str | Path | None,
    dataset_dir: str | Path | None,
    output_dir: str | Path | None,
) -> ExperimentPaths:
    calibration = resolve_path(
        calibration_dir,
        DEFAULT_CALIBRATION_DIR,
    )

    dataset = resolve_path(
        dataset_dir,
        DEFAULT_DATASET_DIR,
    )

    output = resolve_path(
        output_dir,
        DEFAULT_OUTPUT_DIR,
    )

    return ExperimentPaths(
        calibration_dir=calibration,
        calibration_data_dir=(
            calibration
            / "data"
        ),
        dataset_dir=dataset,
        output_dir=output,
    )


def read_json(
    path: Path,
) -> Any:
    with path.open(
        "r",
        encoding="utf-8",
    ) as handle:
        return json.load(
            handle
        )


def write_json(
    path: Path,
    value: Any,
) -> None:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with path.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            value,
            handle,
            indent=2,
            sort_keys=True,
        )

        handle.write(
            "\n"
        )


def require_file(
    path: Path,
) -> Path:
    if not path.exists():
        raise FileNotFoundError(
            "Required experiment file does not exist:\n"
            f"  {path}"
        )

    return path


# ---------------------------------------------------------------------------
# Calibration configuration
# ---------------------------------------------------------------------------

def evenly_spaced_level_indices(
    k: int,
    max_k: int,
) -> tuple[int, ...]:
    """
    Return k approximately evenly spaced one-based indices from 1..max_k.
    """
    if not 2 <= k <= max_k:
        raise ValueError(
            f"k must satisfy 2 <= k <= {max_k}; got {k}."
        )

    indices = tuple(
        int(
            round(
                1
                + i
                * (max_k - 1)
                / (k - 1)
            )
        )
        for i in range(k)
    )

    if len(
        set(indices)
    ) != k:
        raise RuntimeError(
            f"Could not construct {k} unique levels "
            f"from 1..{max_k}: {indices}"
        )

    return indices


def load_calibration_config(
    paths: ExperimentPaths,
) -> CalibrationConfig:
    """
    Load the exact parameter levels used by generate_calibration_grid.py.

    This avoids independently reconstructing the master grid in the analysis
    script.
    """
    levels_path = require_file(
        paths.calibration_data_dir
        / "calibration_levels.json"
    )

    payload = read_json(
        levels_path
    )

    if not isinstance(
        payload,
        dict,
    ):
        raise RuntimeError(
            f"{levels_path} must contain a JSON object."
        )

    try:
        max_k = int(
            payload[
                "max_k"
            ]
        )

    except (
        KeyError,
        TypeError,
        ValueError,
    ) as exc:
        raise RuntimeError(
            f"{levels_path} does not contain a valid 'max_k'."
        ) from exc

    if max_k != EXPECTED_MAX_K:
        raise RuntimeError(
            "This experiment expects a k=15 master calibration grid, "
            f"but calibration_levels.json reports max_k={max_k}."
        )

    raw_levels = payload.get(
        "parameter_levels"
    )

    if not isinstance(
        raw_levels,
        dict,
    ):
        raise RuntimeError(
            f"{levels_path} does not contain 'parameter_levels'."
        )

    parameter_levels: Dict[
        str,
        tuple[float, ...],
    ] = {}

    for parameter_name in REQUIRED_PARAMETERS:
        values = raw_levels.get(
            parameter_name
        )

        if not isinstance(
            values,
            list,
        ):
            raise RuntimeError(
                f"{levels_path} does not contain levels for "
                f"{parameter_name!r}."
            )

        try:
            converted = tuple(
                float(value)
                for value
                in values
            )

        except (
            TypeError,
            ValueError,
        ) as exc:
            raise RuntimeError(
                f"Invalid levels for {parameter_name!r}."
            ) from exc

        if len(
            converted
        ) != max_k:
            raise RuntimeError(
                f"{parameter_name!r} has {len(converted)} levels; "
                f"expected {max_k}."
            )

        parameter_levels[
            parameter_name
        ] = converted

    level_sets: Dict[
        str,
        tuple[int, ...],
    ] = {
        f"k{k}": (
            evenly_spaced_level_indices(
                k,
                max_k,
            )
        )
        for k
        in K_VALUES
    }

    return CalibrationConfig(
        max_k=max_k,
        k_values=K_VALUES,
        level_sets=level_sets,
        parameter_levels=parameter_levels,
        reference_k=f"k{max_k}",
    )


# ---------------------------------------------------------------------------
# Generic record handling
# ---------------------------------------------------------------------------

def flatten_records(
    value: Any,
) -> List[Dict[str, Any]]:
    """Convert common JSON shapes into a list of dictionaries."""
    if isinstance(
        value,
        list,
    ):
        return [
            item
            for item
            in value
            if isinstance(
                item,
                dict,
            )
        ]

    if isinstance(
        value,
        dict,
    ):
        for key in (
            "records",
            "examples",
            "data",
            "results",
            "homes",
        ):
            nested = value.get(
                key
            )

            if isinstance(
                nested,
                list,
            ):
                return [
                    item
                    for item
                    in nested
                    if isinstance(
                        item,
                        dict,
                    )
                ]

        if all(
            isinstance(
                item,
                dict,
            )
            for item
            in value.values()
        ):
            records = []

            for key, item in value.items():
                record = dict(
                    item
                )

                record.setdefault(
                    "example_id",
                    key,
                )

                record.setdefault(
                    "id",
                    key,
                )

                records.append(
                    record
                )

            return records

    return []


def get_identifier(
    record: Dict[str, Any],
) -> Optional[str]:
    for key in (
        "example_id",
        "id",
        "home_id",
        "name",
        "folder",
        "address_folder",
        "simulation_name",
    ):
        value = record.get(
            key
        )

        if value is not None:
            return str(
                value
            )

    return None


def get_nested(
    record: Dict[str, Any],
    path: Sequence[str],
) -> Optional[Any]:
    current: Any = record

    for part in path:
        if (
            not isinstance(
                current,
                dict,
            )
            or part
            not in current
        ):
            return None

        current = current[
            part
        ]

    return current


def as_float(
    value: Any,
) -> Optional[float]:
    try:
        if value is None:
            return None

        return float(
            value
        )

    except (
        TypeError,
        ValueError,
    ):
        return None


# ---------------------------------------------------------------------------
# Calibration artifacts
# ---------------------------------------------------------------------------

def calibration_file_paths(
    paths: ExperimentPaths,
) -> tuple[
    Path,
    Path,
    Path,
]:
    meta_path = require_file(
        paths.calibration_data_dir
        / "calibration_meta.json"
    )

    stats_path = require_file(
        paths.calibration_data_dir
        / "summary_stats.json"
    )

    runtime_path = require_file(
        paths.calibration_data_dir
        / "calibration_runtime.json"
    )

    return (
        meta_path,
        stats_path,
        runtime_path,
    )


def load_calibration_data(
    paths: ExperimentPaths,
) -> CalibrationData:
    """
    Load all large calibration artifacts exactly once.
    """
    (
        meta_path,
        stats_path,
        runtime_path,
    ) = calibration_file_paths(
        paths
    )

    meta_payload = read_json(
        meta_path
    )

    stats_payload = read_json(
        stats_path
    )

    runtime_payload = read_json(
        runtime_path
    )

    meta_records = flatten_records(
        meta_payload
    )

    stat_records = flatten_records(
        stats_payload
    )

    if not isinstance(
        runtime_payload,
        dict,
    ):
        raise RuntimeError(
            f"{runtime_path} must contain a JSON object."
        )

    raw_jobs = runtime_payload.get(
        "jobs"
    )

    if not isinstance(
        raw_jobs,
        dict,
    ):
        raise RuntimeError(
            f"{runtime_path} does not contain a 'jobs' timing dictionary."
        )

    runtime_jobs: Dict[
        str,
        Dict[str, Any],
    ] = {}

    for name, record in raw_jobs.items():
        if isinstance(
            record,
            dict,
        ):
            runtime_jobs[
                str(name)
            ] = record

    print(
        f"      {len(meta_records):,} metadata records"
    )

    print(
        f"      {len(stat_records):,} summary-stat records"
    )

    print(
        f"      {len(runtime_jobs):,} runtime records"
    )

    return CalibrationData(
        meta_records=meta_records,
        stat_records=stat_records,
        runtime_jobs=runtime_jobs,
    )


# ---------------------------------------------------------------------------
# Calibration-level handling
# ---------------------------------------------------------------------------

def nearest_level(
    parameter_name: str,
    value: Any,
    config: CalibrationConfig,
) -> Optional[int]:
    """Find the nearest master-grid level for one physical parameter."""
    numeric_value = as_float(
        value
    )

    if numeric_value is None:
        return None

    levels = config.parameter_levels[
        parameter_name
    ]

    index = min(
        range(
            len(levels)
        ),
        key=lambda i: abs(
            levels[i]
            - numeric_value
        ),
    )

    return (
        index
        + 1
    )


def extract_calibration_levels(
    record: Dict[str, Any],
    config: CalibrationConfig,
) -> Optional[Dict[str, int]]:
    """Read or infer one-based master-grid levels."""
    explicit = record.get(
        "ordinal_levels"
    )

    if isinstance(
        explicit,
        dict,
    ):
        explicit_levels = {
            "wall": as_float(
                explicit.get(
                    "wall_r_value"
                )
            ),
            "roof": as_float(
                explicit.get(
                    "roof_r_value"
                )
            ),
            "heating": as_float(
                explicit.get(
                    "hvac_heating_cop"
                )
            ),
            "cooling": as_float(
                explicit.get(
                    "hvac_cooling_cop"
                )
            ),
        }

        if all(
            value is not None
            for value
            in explicit_levels.values()
        ):
            levels = {
                key: int(
                    value
                )
                for key, value
                in explicit_levels.items()
            }

            if all(
                1
                <= value
                <= config.max_k
                for value
                in levels.values()
            ):
                return levels

    levels = {
        "wall": nearest_level(
            "wall_r_value",
            record.get(
                "wall_r_value"
            ),
            config,
        ),
        "roof": nearest_level(
            "roof_r_value",
            record.get(
                "roof_r_value"
            ),
            config,
        ),
        "heating": nearest_level(
            "hvac_heating_cop",
            record.get(
                "hvac_heating_cop"
            ),
            config,
        ),
        "cooling": nearest_level(
            "hvac_cooling_cop",
            record.get(
                "hvac_cooling_cop"
            ),
            config,
        ),
    }

    if any(
        value is None
        for value
        in levels.values()
    ):
        return None

    return {
        key: int(
            value
        )
        for key, value
        in levels.items()
        if value is not None
    }


def level_position(
    level: int,
    max_k: int,
) -> float:
    """Map a master-grid level to its semantic position in [0, 1]."""
    if not 1 <= level <= max_k:
        raise ValueError(
            f"level must be in 1..{max_k}; got {level}."
        )

    return (
        level
        - 1
    ) / (
        max_k
        - 1
    )


# ---------------------------------------------------------------------------
# Simulation-stat extraction
# ---------------------------------------------------------------------------

def resolve_sim_block(
    record: Dict[str, Any],
    sim_var: str,
) -> Optional[Any]:
    if sim_var in record:
        return record[
            sim_var
        ]

    wanted = sim_var.strip()

    by_stripped = {
        str(key).strip(): value
        for key, value
        in record.items()
    }

    if wanted in by_stripped:
        return by_stripped[
            wanted
        ]

    by_lower = {
        str(key).strip().lower(): value
        for key, value
        in record.items()
    }

    if wanted.lower() in by_lower:
        return by_lower[
            wanted.lower()
        ]

    matches = [
        (
            str(key),
            value,
        )
        for key, value
        in record.items()
        if str(
            key
        ).strip().endswith(
            wanted
        )
    ]

    if len(
        matches
    ) == 1:
        return matches[
            0
        ][1]

    if len(
        matches
    ) > 1:
        return sorted(
            matches,
            key=lambda item: len(
                item[0]
            ),
        )[0][1]

    return None


def extract_stat_value(
    record: Dict[str, Any],
    feature_candidates: Sequence[str],
) -> Optional[float]:
    """
    Extract one numeric simulation statistic.

    The newly generated calibration summaries expose "mean", which is preferred.
    Additional aliases are retained for compatibility with older dataset files.
    """
    stat_keys = (
        "mean",
        "average",
        "avg",
        "value",
        "min",
        "max",
        "std",
    )

    for candidate in feature_candidates:
        block = resolve_sim_block(
            record,
            candidate,
        )

        if isinstance(
            block,
            dict,
        ):
            for stat_key in stat_keys:
                numeric_value = as_float(
                    block.get(
                        stat_key
                    )
                )

                if numeric_value is not None:
                    return numeric_value

        else:
            numeric_value = as_float(
                block
            )

            if numeric_value is not None:
                return numeric_value

    for container_key in (
        "features",
        "summary",
        "summary_stats",
        "stats",
        "outputs",
    ):
        container = record.get(
            container_key
        )

        if not isinstance(
            container,
            dict,
        ):
            continue

        for candidate in feature_candidates:
            block = resolve_sim_block(
                container,
                candidate,
            )

            if isinstance(
                block,
                dict,
            ):
                for stat_key in stat_keys:
                    numeric_value = as_float(
                        block.get(
                            stat_key
                        )
                    )

                    if numeric_value is not None:
                        return numeric_value

            else:
                numeric_value = as_float(
                    block
                )

                if numeric_value is not None:
                    return numeric_value

    return None


# ---------------------------------------------------------------------------
# Shared calibration-row preparation
# ---------------------------------------------------------------------------

def build_stat_index(
    stat_records: Sequence[
        Dict[str, Any]
    ],
) -> Dict[
    str,
    Dict[str, Any],
]:
    """Index summary-stat records once by calibration ID."""
    result: Dict[
        str,
        Dict[str, Any],
    ] = {}

    for record in stat_records:
        identifier = get_identifier(
            record
        )

        if identifier is not None:
            result[
                identifier
            ] = record

    return result


def build_raw_calibration_row(
    meta_record: Dict[str, Any],
    stats_by_id: Dict[
        str,
        Dict[str, Any],
    ],
    config: CalibrationConfig,
) -> tuple[
    Optional[RawExample],
    Optional[Dict[str, int]],
]:
    """
    Construct one reusable RawExample and its master-grid ordinal levels.
    """
    identifier = get_identifier(
        meta_record
    )

    if identifier is None:
        return (
            None,
            None,
        )

    levels = extract_calibration_levels(
        meta_record,
        config,
    )

    if levels is None:
        return (
            None,
            None,
        )

    stats_record = stats_by_id.get(
        identifier,
        {},
    )

    merged = {
        **stats_record,
        **meta_record,
    }

    sim_hvac = extract_stat_value(
        merged,
        HVAC_SIM_FEATURE_CANDIDATES,
    )

    sim_insulation = extract_stat_value(
        merged,
        INSULATION_SIM_FEATURE_CANDIDATES,
    )

    if (
        sim_hvac is None
        or sim_insulation is None
    ):
        return (
            None,
            None,
        )

    text_hvac = statistics.mean(
        (
            level_position(
                levels[
                    "heating"
                ],
                config.max_k,
            ),
            level_position(
                levels[
                    "cooling"
                ],
                config.max_k,
            ),
        )
    )

    text_insulation = statistics.mean(
        (
            level_position(
                levels[
                    "wall"
                ],
                config.max_k,
            ),
            level_position(
                levels[
                    "roof"
                ],
                config.max_k,
            ),
        )
    )

    return (
        RawExample(
            example_id=identifier,
            text_hvac=float(
                text_hvac
            ),
            text_insulation=float(
                text_insulation
            ),
            sim_hvac=float(
                sim_hvac
            ),
            sim_insulation=float(
                sim_insulation
            ),
        ),
        levels,
    )


def prepare_master_rows(
    data: CalibrationData,
    config: CalibrationConfig,
) -> List[
    tuple[
        RawExample,
        Dict[str, int],
    ]
]:
    """
    Parse calibration examples once and retain both scores and ordinal levels.
    """
    stats_by_id = build_stat_index(
        data.stat_records
    )

    rows: List[
        tuple[
            RawExample,
            Dict[str, int],
        ]
    ] = []

    skipped = 0

    for meta_record in data.meta_records:
        row, levels = (
            build_raw_calibration_row(
                meta_record,
                stats_by_id,
                config,
            )
        )

        if (
            row is None
            or levels is None
        ):
            skipped += 1
            continue

        rows.append(
            (
                row,
                levels,
            )
        )

    if not rows:
        raise RuntimeError(
            "No calibration rows could be constructed. Check "
            "calibration_meta.json and summary_stats.json."
        )

    print(
        f"      {len(rows):,} usable calibration rows"
    )

    if skipped:
        print(
            f"      {skipped:,} rows skipped"
        )

    return rows


# ---------------------------------------------------------------------------
# Calibration-grid subsetting
# ---------------------------------------------------------------------------

def k_sort_key(
    k_name: str,
) -> int:
    """Sort names such as k2, k11, and k15 numerically."""
    if not k_name.startswith(
        "k"
    ):
        raise ValueError(
            f"Invalid calibration-resolution name: {k_name}"
        )

    return int(
        k_name[
            1:
        ]
    )


def load_calibration_rows_by_k(
    master_rows: Sequence[
        tuple[
            RawExample,
            Dict[str, int],
        ]
    ],
    config: CalibrationConfig,
) -> Dict[
    str,
    List[RawExample],
]:
    """
    Subselect every tested grid from the common k=15 master calibration grid.
    """
    allowed_level_sets = {
        k_name: set(
            levels
        )
        for k_name, levels
        in config.level_sets.items()
    }

    rows_by_k: Dict[
        str,
        List[RawExample],
    ] = {
        name: []
        for name
        in config.level_sets
    }

    for row, levels in master_rows:
        level_values = tuple(
            levels.values()
        )

        for (
            k_name,
            allowed,
        ) in allowed_level_sets.items():
            if all(
                level in allowed
                for level
                in level_values
            ):
                rows_by_k[
                    k_name
                ].append(
                    row
                )

    for k_name in sorted(
        rows_by_k,
        key=k_sort_key,
    ):
        rows = rows_by_k[
            k_name
        ]

        expected = (
            len(
                config.level_sets[
                    k_name
                ]
            )
            ** 4
        )

        if not rows:
            raise RuntimeError(
                f"No calibration rows found for {k_name}. "
                "Check that the k=15 calibration run completed."
            )

        if len(
            rows
        ) != expected:
            print(
                f"      {k_name}: "
                f"{len(rows):,}/{expected:,} rows "
                "(WARNING: incomplete)"
            )

        else:
            print(
                f"      {k_name}: "
                f"{len(rows):,}/{expected:,} calibration rows"
            )

    return rows_by_k


# ---------------------------------------------------------------------------
# EnergyPlus runtime aggregation
# ---------------------------------------------------------------------------

def load_energyplus_runtime_by_k(
    master_rows: Sequence[
        tuple[
            RawExample,
            Dict[str, int],
        ]
    ],
    runtime_jobs: Dict[
        str,
        Dict[str, Any],
    ],
    config: CalibrationConfig,
) -> Dict[
    str,
    Dict[str, Any],
]:
    """
    Aggregate measured EnergyPlus runtimes for each k grid.

    Because every smaller grid is a subset of the k=15 master grid, the
    cumulative compute time for k is the sum of the measured durations of the
    exact EnergyPlus simulations included in that subset.
    """
    summaries: Dict[
        str,
        Dict[str, Any],
    ] = {
        k_name: {
            "timed_simulation_jobs": 0,
            "successful_simulation_jobs": 0,
            "energyplus_compute_seconds": 0.0,
        }
        for k_name
        in config.level_sets
    }

    allowed_level_sets = {
        k_name: set(
            levels
        )
        for k_name, levels
        in config.level_sets.items()
    }

    for row, levels in master_rows:
        job = runtime_jobs.get(
            row.example_id
        )

        if not isinstance(
            job,
            dict,
        ):
            continue

        runtime_seconds = as_float(
            job.get(
                "runtime_seconds"
            )
        )

        if runtime_seconds is None:
            continue

        succeeded = bool(
            job.get(
                "succeeded",
                False,
            )
        )

        level_values = tuple(
            levels.values()
        )

        for (
            k_name,
            allowed,
        ) in allowed_level_sets.items():
            if all(
                level in allowed
                for level
                in level_values
            ):
                summary = summaries[
                    k_name
                ]

                summary[
                    "timed_simulation_jobs"
                ] += 1

                summary[
                    "energyplus_compute_seconds"
                ] += runtime_seconds

                if succeeded:
                    summary[
                        "successful_simulation_jobs"
                    ] += 1

    for (
        k_name,
        summary,
    ) in summaries.items():
        expected_jobs = (
            len(
                config.level_sets[
                    k_name
                ]
            )
            ** 4
        )

        timed_jobs = int(
            summary[
                "timed_simulation_jobs"
            ]
        )

        compute_seconds = float(
            summary[
                "energyplus_compute_seconds"
            ]
        )

        summary[
            "expected_simulation_jobs"
        ] = expected_jobs

        summary[
            "runtime_measurement_coverage"
        ] = (
            timed_jobs
            / expected_jobs
            if expected_jobs
            else float(
                "nan"
            )
        )

        summary[
            "mean_energyplus_seconds_per_job"
        ] = (
            compute_seconds
            / timed_jobs
            if timed_jobs
            else float(
                "nan"
            )
        )

    return summaries


# ---------------------------------------------------------------------------
# Calibration and fusion
# ---------------------------------------------------------------------------

def safe_std(
    values: Sequence[float],
) -> float:
    if len(
        values
    ) < 2:
        return 1.0

    std = statistics.pstdev(
        values
    )

    if math.isclose(
        std,
        0.0,
        abs_tol=1e-12,
    ):
        return 1.0

    return std


def build_scaler(
    rows: Sequence[RawExample],
    concept: str,
) -> Scaler:
    if concept == "hvac":
        text_values = [
            row.text_hvac
            for row
            in rows
        ]

        sim_values = [
            row.sim_hvac
            for row
            in rows
        ]

    elif concept == "insulation":
        text_values = [
            row.text_insulation
            for row
            in rows
        ]

        sim_values = [
            row.sim_insulation
            for row
            in rows
        ]

    else:
        raise ValueError(
            f"Unknown concept: {concept}"
        )

    return Scaler(
        text_mean=statistics.mean(
            text_values
        ),
        text_std=safe_std(
            text_values
        ),
        sim_mean=statistics.mean(
            sim_values
        ),
        sim_std=safe_std(
            sim_values
        ),
    )


def sigmoid(
    value: float,
) -> float:
    value = max(
        -3.0,
        min(
            3.0,
            value,
        ),
    )

    return (
        1.0
        / (
            1.0
            + math.exp(
                -value
            )
        )
    )


def fuse(
    text_value: float,
    sim_value: float,
    scaler: Scaler,
) -> float:
    text_z = (
        text_value
        - scaler.text_mean
    ) / scaler.text_std

    sim_z = (
        sim_value
        - scaler.sim_mean
    ) / scaler.sim_std

    return sigmoid(
        0.5
        * text_z
        + 0.5
        * sim_z
    )


# ---------------------------------------------------------------------------
# Target dataset loading
# ---------------------------------------------------------------------------

def extract_text_score(
    record: Dict[str, Any],
    concept: str,
) -> Optional[float]:
    candidate_paths = [
        (
            "text_scores",
            concept,
        ),
        (
            "gpt_scores",
            concept,
        ),
        (
            "llm_scores",
            concept,
        ),
        (
            "raw_scores",
            f"text_{concept}",
        ),
        (
            "raw",
            f"text_{concept}",
        ),
        (
            "scores",
            concept,
        ),
        (
            concept,
            "text_score",
        ),
        (
            concept,
            "score",
        ),
    ]

    candidate_keys = (
        f"text_{concept}",
        f"{concept}_text",
        f"{concept}_text_score",
        f"mean_{concept}",
    )

    for key in candidate_keys:
        value = as_float(
            record.get(
                key
            )
        )

        if value is not None:
            return value

    for path in candidate_paths:
        value = as_float(
            get_nested(
                record,
                path,
            )
        )

        if value is not None:
            return value

    return None


def extract_sim_score(
    record: Dict[str, Any],
    concept: str,
) -> Optional[float]:
    if concept == "hvac":
        candidates = HVAC_SIM_FEATURE_CANDIDATES

        candidate_keys = (
            "sim_hvac",
            "hvac_sim",
            "hvac_electricity",
            "mean_hvac_sim",
        )

    elif concept == "insulation":
        candidates = INSULATION_SIM_FEATURE_CANDIDATES

        candidate_keys = (
            "sim_insulation",
            "insulation_sim",
            "heating_coil",
            "mean_insulation_sim",
        )

    else:
        raise ValueError(
            f"Unknown concept: {concept}"
        )

    for key in candidate_keys:
        value = as_float(
            record.get(
                key
            )
        )

        if value is not None:
            return value

    value = extract_stat_value(
        record,
        candidates,
    )

    if value is not None:
        return value

    candidate_paths = [
        (
            "raw_scores",
            f"sim_{concept}",
        ),
        (
            "raw",
            f"sim_{concept}",
        ),
        (
            "simulation_scores",
            concept,
        ),
        (
            "simulation",
            concept,
        ),
    ]

    for path in candidate_paths:
        value = as_float(
            get_nested(
                record,
                path,
            )
        )

        if value is not None:
            return value

    return None


def load_target_examples_from_dataset(
    dataset_dir: Path,
) -> List[RawExample]:
    """Extract reusable raw scorer values from the Synthetic Homes dataset."""
    if not dataset_dir.exists():
        print(
            f"      Dataset directory does not exist: "
            f"{dataset_dir}"
        )

        return []

    examples: List[
        RawExample
    ] = []

    seen: set[str] = set()

    json_files = sorted(
        dataset_dir.rglob(
            "*.json"
        )
    )

    print(
        f"      scanning {len(json_files):,} JSON files"
    )

    for path in json_files:
        try:
            raw_json = read_json(
                path
            )

        except (
            json.JSONDecodeError,
            OSError,
        ):
            continue

        records = flatten_records(
            raw_json
        )

        if (
            not records
            and isinstance(
                raw_json,
                dict,
            )
        ):
            records = [
                raw_json
            ]

        for index, record in enumerate(
            records
        ):
            if not isinstance(
                record,
                dict,
            ):
                continue

            identifier = (
                get_identifier(
                    record
                )
                or (
                    f"{path.parent.name}:"
                    f"{path.name}:"
                    f"{index}"
                )
            )

            text_hvac = extract_text_score(
                record,
                "hvac",
            )

            text_insulation = extract_text_score(
                record,
                "insulation",
            )

            sim_hvac = extract_sim_score(
                record,
                "hvac",
            )

            sim_insulation = extract_sim_score(
                record,
                "insulation",
            )

            if None in (
                text_hvac,
                text_insulation,
                sim_hvac,
                sim_insulation,
            ):
                continue

            if identifier in seen:
                continue

            seen.add(
                identifier
            )

            examples.append(
                RawExample(
                    example_id=identifier,
                    text_hvac=float(
                        text_hvac
                    ),
                    text_insulation=float(
                        text_insulation
                    ),
                    sim_hvac=float(
                        sim_hvac
                    ),
                    sim_insulation=float(
                        sim_insulation
                    ),
                )
            )

    print(
        f"      loaded {len(examples):,} target examples"
    )

    return examples


# ---------------------------------------------------------------------------
# Label construction
# ---------------------------------------------------------------------------

def label_examples(
    examples: Sequence[RawExample],
    k_name: str,
    hvac_scaler: Scaler,
    insulation_scaler: Scaler,
) -> List[LabeledExample]:
    labeled: List[
        LabeledExample
    ] = []

    for example in examples:
        hvac_label = fuse(
            example.text_hvac,
            example.sim_hvac,
            hvac_scaler,
        )

        insulation_label = fuse(
            example.text_insulation,
            example.sim_insulation,
            insulation_scaler,
        )

        overall_label = statistics.mean(
            (
                hvac_label,
                insulation_label,
            )
        )

        labeled.append(
            LabeledExample(
                example_id=example.example_id,
                k_name=k_name,
                hvac_label=hvac_label,
                insulation_label=insulation_label,
                overall_label=overall_label,
            )
        )

    return labeled


# ---------------------------------------------------------------------------
# Comparison metrics
# ---------------------------------------------------------------------------

def rankdata(
    values: Sequence[float],
) -> List[float]:
    """Average ranks for ties, 1-indexed."""
    sorted_pairs = sorted(
        enumerate(
            values
        ),
        key=lambda pair: pair[1],
    )

    ranks = [
        0.0
    ] * len(
        values
    )

    i = 0

    while i < len(
        sorted_pairs
    ):
        j = i

        while (
            j + 1
            < len(
                sorted_pairs
            )
            and sorted_pairs[
                j + 1
            ][1]
            == sorted_pairs[
                i
            ][1]
        ):
            j += 1

        average_rank = (
            i + 1
            + j + 1
        ) / 2.0

        for index in range(
            i,
            j + 1,
        ):
            ranks[
                sorted_pairs[
                    index
                ][0]
            ] = average_rank

        i = (
            j + 1
        )

    return ranks


def pearson(
    x_values: Sequence[float],
    y_values: Sequence[float],
) -> float:
    if (
        len(
            x_values
        )
        != len(
            y_values
        )
        or len(
            x_values
        )
        < 2
    ):
        return float(
            "nan"
        )

    x_mean = statistics.mean(
        x_values
    )

    y_mean = statistics.mean(
        y_values
    )

    numerator = sum(
        (
            x - x_mean
        )
        * (
            y - y_mean
        )
        for x, y
        in zip(
            x_values,
            y_values,
        )
    )

    x_denominator = math.sqrt(
        sum(
            (
                x - x_mean
            )
            ** 2
            for x
            in x_values
        )
    )

    y_denominator = math.sqrt(
        sum(
            (
                y - y_mean
            )
            ** 2
            for y
            in y_values
        )
    )

    denominator = (
        x_denominator
        * y_denominator
    )

    if math.isclose(
        denominator,
        0.0,
        abs_tol=1e-12,
    ):
        return float(
            "nan"
        )

    return (
        numerator
        / denominator
    )


def spearman(
    x_values: Sequence[float],
    y_values: Sequence[float],
) -> float:
    return pearson(
        rankdata(
            x_values
        ),
        rankdata(
            y_values
        ),
    )


def top_fraction_overlap(
    candidate_scores: Dict[str, float],
    reference_scores: Dict[str, float],
    fraction: float = 0.10,
) -> float:
    common_ids = sorted(
        set(
            candidate_scores
        )
        & set(
            reference_scores
        )
    )

    if not common_ids:
        return float(
            "nan"
        )

    top_n = max(
        1,
        math.ceil(
            len(
                common_ids
            )
            * fraction
        ),
    )

    candidate_top = {
        example_id
        for example_id, _
        in sorted(
            (
                (
                    example_id,
                    candidate_scores[
                        example_id
                    ],
                )
                for example_id
                in common_ids
            ),
            key=lambda pair: pair[1],
            reverse=True,
        )[
            :top_n
        ]
    }

    reference_top = {
        example_id
        for example_id, _
        in sorted(
            (
                (
                    example_id,
                    reference_scores[
                        example_id
                    ],
                )
                for example_id
                in common_ids
            ),
            key=lambda pair: pair[1],
            reverse=True,
        )[
            :top_n
        ]
    }

    return (
        len(
            candidate_top
            & reference_top
        )
        / top_n
    )


def summarize_against_reference(
    labels_by_k: Dict[
        str,
        List[LabeledExample],
    ],
    reference_k: str,
) -> List[Dict[str, Any]]:
    """Compare every tested resolution with the k=15 reference."""
    if not labels_by_k:
        return []

    if reference_k not in labels_by_k:
        raise KeyError(
            f"Reference resolution {reference_k!r} is not available."
        )

    reference_k_value = k_sort_key(
        reference_k
    )

    reference = {
        row.example_id: row.overall_label
        for row
        in labels_by_k[
            reference_k
        ]
    }

    summaries: List[
        Dict[str, Any]
    ] = []

    for k_name in sorted(
        labels_by_k,
        key=k_sort_key,
    ):
        rows = labels_by_k[
            k_name
        ]

        candidate = {
            row.example_id: row.overall_label
            for row
            in rows
        }

        common_ids = sorted(
            set(
                candidate
            )
            & set(
                reference
            )
        )

        candidate_values = [
            candidate[
                example_id
            ]
            for example_id
            in common_ids
        ]

        reference_values = [
            reference[
                example_id
            ]
            for example_id
            in common_ids
        ]

        if common_ids:
            absolute_differences = [
                abs(
                    candidate[
                        example_id
                    ]
                    - reference[
                        example_id
                    ]
                )
                for example_id
                in common_ids
            ]

            mean_abs_diff = statistics.mean(
                absolute_differences
            )

            max_abs_diff = max(
                absolute_differences
            )

        else:
            mean_abs_diff = float(
                "nan"
            )

            max_abs_diff = float(
                "nan"
            )

        k_value = k_sort_key(
            k_name
        )

        summaries.append(
            {
                "calibration_resolution": k_name,
                "reference_resolution": reference_k,
                "is_reference": (
                    k_name
                    == reference_k
                ),
                "num_calibration_points": (
                    k_value
                    ** 4
                ),
                "fraction_of_reference_grid": (
                    (
                        k_value
                        / reference_k_value
                    )
                    ** 4
                ),
                "num_target_examples": len(
                    common_ids
                ),
                "spearman_vs_reference": spearman(
                    candidate_values,
                    reference_values,
                ),
                "mean_abs_diff_vs_reference": (
                    mean_abs_diff
                ),
                "max_abs_diff_vs_reference": (
                    max_abs_diff
                ),
                "top_10_percent_overlap_vs_reference": (
                    top_fraction_overlap(
                        candidate,
                        reference,
                        fraction=0.10,
                    )
                ),
                "top_20_percent_overlap_vs_reference": (
                    top_fraction_overlap(
                        candidate,
                        reference,
                        fraction=0.20,
                    )
                ),
            }
        )

    return summaries


# ---------------------------------------------------------------------------
# Result writing
# ---------------------------------------------------------------------------

def write_labeled_csv(
    path: Path,
    labels_by_k: Dict[
        str,
        List[LabeledExample],
    ],
) -> None:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with path.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=(
                "example_id",
                "calibration_resolution",
                "hvac_label",
                "insulation_label",
                "overall_label",
            ),
        )

        writer.writeheader()

        for k_name in sorted(
            labels_by_k,
            key=k_sort_key,
        ):
            for row in labels_by_k[
                k_name
            ]:
                writer.writerow(
                    {
                        "example_id": row.example_id,
                        "calibration_resolution": row.k_name,
                        "hvac_label": row.hvac_label,
                        "insulation_label": row.insulation_label,
                        "overall_label": row.overall_label,
                    }
                )


def write_summary_csv(
    path: Path,
    summary_rows: Sequence[
        Dict[str, Any]
    ],
) -> None:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with path.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=(
                "calibration_resolution",
                "reference_resolution",
                "is_reference",
                "num_calibration_points",
                "fraction_of_reference_grid",
                "num_target_examples",
                "spearman_vs_reference",
                "mean_abs_diff_vs_reference",
                "max_abs_diff_vs_reference",
                "top_10_percent_overlap_vs_reference",
                "top_20_percent_overlap_vs_reference",
                "timed_simulation_jobs",
                "successful_simulation_jobs",
                "expected_simulation_jobs",
                "runtime_measurement_coverage",
                "energyplus_compute_seconds",
                "mean_energyplus_seconds_per_job",
                "scaler_build_wall_time_seconds",
                "target_labeling_wall_time_seconds",
                "analysis_wall_time_seconds",
            ),
        )

        writer.writeheader()

        for row in summary_rows:
            writer.writerow(
                row
            )


# ---------------------------------------------------------------------------
# Main experiment
# ---------------------------------------------------------------------------

def run_experiment(
    paths: ExperimentPaths,
) -> None:
    experiment_started = (
        time.perf_counter()
    )

    paths.output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    print()
    print(
        "=" * 72
    )
    print(
        "Calibration-resolution sensitivity experiment"
    )
    print(
        "=" * 72
    )
    print(
        f"Calibration directory: "
        f"{paths.calibration_dir}"
    )
    print(
        f"Dataset directory:     "
        f"{paths.dataset_dir}"
    )
    print(
        f"Output directory:      "
        f"{paths.output_dir}"
    )
    print(
        "=" * 72
    )
    print()

    # ------------------------------------------------------------------
    # 1. Configuration
    # ------------------------------------------------------------------

    with stage(
        1,
        6,
        "Loading calibration configuration",
    ):
        config = load_calibration_config(
            paths
        )

        print(
            f"      master resolution: "
            f"k={config.max_k}"
        )

        print(
            "      tested resolutions: "
            + ", ".join(
                str(k)
                for k
                in config.k_values
            )
        )

    # ------------------------------------------------------------------
    # 2. Parse large calibration artifacts once.
    # ------------------------------------------------------------------

    with stage(
        2,
        6,
        "Loading calibration data",
    ):
        calibration_data = (
            load_calibration_data(
                paths
            )
        )

        master_rows = (
            prepare_master_rows(
                calibration_data,
                config,
            )
        )

    # ------------------------------------------------------------------
    # 3. Construct k subsets and aggregate runtimes.
    # ------------------------------------------------------------------

    with stage(
        3,
        6,
        "Constructing calibration subsets",
    ):
        rows_by_k = (
            load_calibration_rows_by_k(
                master_rows,
                config,
            )
        )

        energyplus_runtime_by_k = (
            load_energyplus_runtime_by_k(
                master_rows,
                calibration_data.runtime_jobs,
                config,
            )
        )

    # ------------------------------------------------------------------
    # 4. Build calibration scalers.
    # ------------------------------------------------------------------

    with stage(
        4,
        6,
        "Building calibration scalers",
    ):
        scalers: Dict[
            str,
            Dict[str, Scaler],
        ] = {}

        scaler_runtime_by_k: Dict[
            str,
            float,
        ] = {}

        for k_name in sorted(
            rows_by_k,
            key=k_sort_key,
        ):
            started = (
                time.perf_counter()
            )

            rows = rows_by_k[
                k_name
            ]

            scalers[
                k_name
            ] = {
                "hvac": build_scaler(
                    rows,
                    "hvac",
                ),
                "insulation": build_scaler(
                    rows,
                    "insulation",
                ),
            }

            scaler_runtime_by_k[
                k_name
            ] = (
                time.perf_counter()
                - started
            )

            print(
                f"      {k_name}: "
                f"{scaler_runtime_by_k[k_name]:.6f} s"
            )

    # ------------------------------------------------------------------
    # 5. Load target examples and construct labels.
    # ------------------------------------------------------------------

    with stage(
        5,
        6,
        "Loading and labeling target examples",
    ):
        target_examples = (
            load_target_examples_from_dataset(
                paths.dataset_dir
            )
        )

        target_source = "dataset"

        if not target_examples:
            print(
                "      WARNING: no reusable raw target examples "
                "were found."
            )

            print(
                "      using the full k=15 calibration grid "
                "as the common target set"
            )

            target_examples = [
                row
                for row, _
                in master_rows
            ]

            target_source = (
                "calibration_grid_fallback"
            )

            print(
                f"      fallback target examples: "
                f"{len(target_examples):,}"
            )

        labels_by_k: Dict[
            str,
            List[LabeledExample],
        ] = {}

        labeling_runtime_by_k: Dict[
            str,
            float,
        ] = {}

        for k_name in sorted(
            config.level_sets,
            key=k_sort_key,
        ):
            started = (
                time.perf_counter()
            )

            labels_by_k[
                k_name
            ] = label_examples(
                target_examples,
                k_name,
                scalers[
                    k_name
                ][
                    "hvac"
                ],
                scalers[
                    k_name
                ][
                    "insulation"
                ],
            )

            labeling_runtime_by_k[
                k_name
            ] = (
                time.perf_counter()
                - started
            )

            print(
                f"      {k_name}: "
                f"{len(labels_by_k[k_name]):,} labels "
                f"in {labeling_runtime_by_k[k_name]:.6f} s"
            )

    # ------------------------------------------------------------------
    # 6. Compare against k=15 and write results.
    # ------------------------------------------------------------------

    with stage(
        6,
        6,
        "Computing sensitivity metrics and writing results",
    ):
        reference_k = (
            config.reference_k
        )

        summary_rows = (
            summarize_against_reference(
                labels_by_k,
                reference_k=reference_k,
            )
        )

        for row in summary_rows:
            k_name = str(
                row[
                    "calibration_resolution"
                ]
            )

            row.update(
                energyplus_runtime_by_k[
                    k_name
                ]
            )

            row[
                "scaler_build_wall_time_seconds"
            ] = scaler_runtime_by_k[
                k_name
            ]

            row[
                "target_labeling_wall_time_seconds"
            ] = labeling_runtime_by_k[
                k_name
            ]

            row[
                "analysis_wall_time_seconds"
            ] = (
                scaler_runtime_by_k[
                    k_name
                ]
                + labeling_runtime_by_k[
                    k_name
                ]
            )

        summary_csv_path = (
            paths.output_dir
            / "k_sensitivity_summary.csv"
        )

        labels_csv_path = (
            paths.output_dir
            / "k_sensitivity_labels.csv"
        )

        summary_json_path = (
            paths.output_dir
            / "k_sensitivity_summary.json"
        )

        write_summary_csv(
            summary_csv_path,
            summary_rows,
        )

        write_labeled_csv(
            labels_csv_path,
            labels_by_k,
        )

        write_json(
            summary_json_path,
            {
                "target_source": target_source,
                "num_target_examples": len(
                    target_examples
                ),
                "reference_resolution": reference_k,
                "max_k": config.max_k,
                "tested_k_values": list(
                    config.k_values
                ),
                "runtime_notes": {
                    "energyplus_compute_seconds": (
                        "Sum of measured per-job EnergyPlus runtimes for the "
                        "exact simulations included in each k-grid. This is "
                        "cumulative compute time, not parallel batch wall time."
                    ),
                    "analysis_wall_time_seconds": (
                        "Measured in-process wall time for constructing both "
                        "calibration scalers and labeling the common target set "
                        "at each resolution."
                    ),
                },
                "level_sets": {
                    key: list(
                        value
                    )
                    for key, value
                    in config.level_sets.items()
                },
                "parameter_levels": {
                    key: list(
                        value
                    )
                    for key, value
                    in config.parameter_levels.items()
                },
                "scalers": {
                    k_name: {
                        concept: {
                            "text_mean": scaler.text_mean,
                            "text_std": scaler.text_std,
                            "sim_mean": scaler.sim_mean,
                            "sim_std": scaler.sim_std,
                        }
                        for concept, scaler
                        in concept_scalers.items()
                    }
                    for k_name, concept_scalers
                    in scalers.items()
                },
                "summary": summary_rows,
            },
        )

    # ------------------------------------------------------------------
    # Console summary
    # ------------------------------------------------------------------

    print(
        "=" * 72
    )
    print(
        "Calibration-resolution sensitivity summary "
        f"(reference={reference_k})"
    )
    print(
        "=" * 72
    )

    for row in summary_rows:
        print(
            f"{row['calibration_resolution']:>3}: "
            f"grid={row['num_calibration_points']:>6,}, "
            f"n={row['num_target_examples']:>6,}, "
            f"spearman={row['spearman_vs_reference']:.4f}, "
            f"mean_abs_diff="
            f"{row['mean_abs_diff_vs_reference']:.4f}, "
            f"top10="
            f"{row['top_10_percent_overlap_vs_reference']:.4f}, "
            f"E+={row['energyplus_compute_seconds']:.2f}s"
        )

    total_elapsed = (
        time.perf_counter()
        - experiment_started
    )

    print()
    print(
        "Wrote:"
    )
    print(
        f"  {summary_csv_path}"
    )
    print(
        f"  {labels_csv_path}"
    )
    print(
        f"  {summary_json_path}"
    )

    print()
    print(
        f"Total analysis wall time: "
        f"{total_elapsed:.2f} s"
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate sensitivity of the calibration-first supervision "
            "signal to calibration-grid resolution k."
        )
    )

    parser.add_argument(
        "--calibration-dir",
        default=None,
        help=(
            "Calibration-grid output directory produced by "
            "generate_calibration_grid.py. Default: calibration_grid/ "
            "next to this script."
        ),
    )

    parser.add_argument(
        "--dataset-dir",
        default=None,
        help=(
            "Synthetic Homes target dataset directory. Default: dataset/ "
            "next to this script."
        ),
    )

    parser.add_argument(
        "--output-dir",
        default=None,
        help=(
            "Directory for sensitivity-analysis outputs. Default: "
            "k_sensitivity_results/ next to this script."
        ),
    )

    args = parser.parse_args()

    paths = build_paths(
        calibration_dir=(
            args.calibration_dir
        ),
        dataset_dir=(
            args.dataset_dir
        ),
        output_dir=(
            args.output_dir
        ),
    )

    run_experiment(
        paths
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )